### ISSUE TITLE
about ILSVRC2012_mapping.txt

### ISSUE THREAD

**Issue by zchrissirhcz** [fh295/semanticCNN#2]
Hi,

Is this file ILSVRC2012_mapping.txt generated by yourself? or downloaded from somewhere else? I can't find this file on ImageNet official site.

Actually, I find in the devkit there is:
`D:\data\imagenet\ILSVRC2012_devkit_t12\data\ILSVRC2012_validation_ground_truth.txt`
which gives:
```
490
361
171
822
```
means the `ILSVRC2012_val_00000001.JPEG` is with "490" as its label. It is a snake, and only use your provided mapping file I can get it's correct label. Very curious.

Thanks.

**Comment by yanghao1126** [comment]
Hi, did you find the ILSVRC2012_mapping.txt on ImageNet official site? 

I find authors changed the ILSVRC2012_mapping.txt, which is different from the previous version.
